disabled_rules:
  - trailing_comma
  - multiple_closures_with_trailing_closure
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - force_cast
  - force_try
  # project-specific exceptions
  - identifier_name  # variables like `s` in BreakOverlayView are intentionally short to preserve animation logic

excluded:
  - DerivedData
  - .build
  - SuperZenUITests
  - SuperZenTests
